# Path to raw expression data (CSV with genes×samples)
expr_file: "data/raw/example_expression.csv"

# Preprocessing
norm_method: "vst"            # "vst" or "log2"
topN:        10000            # number of highest-variance genes to keep

# Soft‐threshold power scanning
powers:      [1,2,3,4,5,6,7,8,9,10,12,14,16,18,20]
tom_type:    "unsigned"       # "unsigned" or "signed"
cor_type:    "pearson"        # "pearson" or "bicor"

# Module detection
deep_split:       2           # dynamicTreeCut sensitivity (0–4)
min_module_size: 30           # smallest module size
merge_height:     0.25        # merge modules whose eigengenes correlate > (1–merge_height)

# Outlier removal & stability
outlier_z:      2.5          # Z-score cutoff for removing sample outliers
bootstrap:      false        # whether to bootstrap for stability
n_boot:         100          # bootstrap iterations if enabled
